import os
from pathlib import Path

import librosa
import soundfile as sf

# Setup environment and model
####################################################

print("=" * 60)
print("Config:")

# Base path for all generated files
THIS_FOLDER = os.path.dirname(__file__)
print("Base folder:", THIS_FOLDER)

CUSTOM_INPUT_PATH = rf"{THIS_FOLDER}\Custom"
Path(CUSTOM_INPUT_PATH).mkdir(parents=True, exist_ok=True)
print("In folder:", CUSTOM_INPUT_PATH)

CUSTOM_OUTPUT_PATH = rf"{THIS_FOLDER}\Datasets\Train\Negative\Custom"
Path(CUSTOM_OUTPUT_PATH).mkdir(parents=True, exist_ok=True)
print("Out folder:", CUSTOM_OUTPUT_PATH)

SAMPLE_RATE = 24000  # Based on clean samples

custom_files = {
    # Key, Filename
    "wigs": rf"{CUSTOM_INPUT_PATH}\Wigs.wav",
    "air_vent": rf"{CUSTOM_INPUT_PATH}\air_vent.wav",
    "nature": rf"{CUSTOM_INPUT_PATH}\nature.wav",
    "streets": rf"{CUSTOM_INPUT_PATH}\streets.wav",
    "white_noise": rf"{CUSTOM_INPUT_PATH}\white_noise.wav",
}


print("=" * 60)
print("Generating custom negative datasets...")

# Iterate over each wanted file.
for key, filepath in custom_files.items():
    print(filepath)

    wavs, wavs_sr = librosa.load(
        filepath,
        sr=None,
        mono=True,
    )

    resampled = wavs
    if wavs_sr != SAMPLE_RATE:
        resampled = librosa.resample(wavs, orig_sr=wavs_sr, target_sr=SAMPLE_RATE)

    # Determine how many samples can be generated by splitting every 3 seconds.
    split_size = SAMPLE_RATE * 3
    count = resampled.size // split_size

    # Generate out folder
    CURR_FOLDER = rf"{CUSTOM_OUTPUT_PATH}\{key}"
    Path(CURR_FOLDER).mkdir(parents=True, exist_ok=True)

    # Split and save samples
    for i in range(count):
        current_start_index = i * split_size
        element = resampled[current_start_index : current_start_index + split_size]
        OUT_FILE = rf"{CURR_FOLDER}\{key}_{i:05d}.wav"
        sf.write(
            OUT_FILE,
            element,
            SAMPLE_RATE,
        )
