; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
extra_configs =
    config/secret.ini

[env:esp32]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ~/Documents/Arduino/libraries
build_flags= 
    '-D WIFI_SSID="${secret.wifi_ssid}"'
    '-D WIFI_PASS="${secret.wifi_pass}"'
